#Creando mi propia action

name: "My action"
description: "Test my action"

inputs:
  message:
    description: "The message to print"
    required: true
    default: "Desde mi action creada, enviando desde el parametro message."

runs:
  using: "composite" 

  steps:
    - name: Hola mundo desde mi action
      run: echo "Amor, ${{ inputs.message }}"
      shell: bash