name: Creando mi propio Runner #Nombre de mi workflow

on: #[push, pull_request] # Mi workflow se va a ejecutar cuando se dispare uno de estos eventos en mi repositorio.
    push:
        branches:
            - main #Ejecuta mi workflow a la hora de hacer un push unicamente a la rama de main.
    pull_request:
        branches:
            - main #O ejecuta mi workflow a la hora de hacer un pull request unicamente a la rama de main.       
jobs: # Primera tarea que va a ejecutar mi workflow.
    build:
        runs-on: self-hosted # Maquina virtual cargada o sistema operativo.

        steps: #Pasos que se van a ejecutar para llevar acabo mi trabajo.
            - name: Creando mi propio runner desde github #Paso 1
              run: echo ls

            - name: touch file #Paso 2
              run: touch file.txt # Con la directiva run podemos ejecutar cualquier comando que se encuentre en nuestra maquina virtual.

            - name: Set text #Paso 3
              run: echo "Hola Thalia" > file.txt  

            - name: Read file #Paso 4
              run: cat file.txt  

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7

            - name: Hola Mundo2
              run: ls -al

