name: MiSegundoWorkFlow #Nombre de mi workflow

on: #[push, pull_request] # Mi workflow se va a ejecutar cuando se dispare uno de estos eventos en mi repositorio.
    push:
        branches:
            - main #Ejecuta mi workflow a la hora de hacer un push unicamente a la rama de main.
    pull_request:
        branches:
            - main #O ejecuta mi workflow a la hora de hacer un pull request unicamente a la rama de main.       
jobs: 
    MiPrimerJob: # Primera tarea que va a ejecutar mi workflow.
        runs-on: ubuntu-latest # Maquina virtual cargada o sistema operativo.
        steps: #Pasos que se van a ejecutar para llevar acabo mi trabajo.
          - name: Imprimiendo el nombre de mi novia
            run: echo "Gabriela Morillo Mendez"
            

            

