name: InstalacionDePaquetes

on: [push]

#run: ls -al #Enlista todos los archivos de mi directorio actual.
#  chmod +x script.sh :Aqui le estoy dando el permiso al archivo para poder ejecutarlo.
#  ./script.sh :Aqui estoy ejecutando el archivo.
jobs:
    
    test-build:   
        runs-on: ubuntu-latest

        steps:
 #           - name: Checkout #En este paso me estoy ubucando en el repositorio  actual
 #             uses: actions/checkout@v2

 #           - name: ls
 #             run: | #Mas abajo se escribe un string multilineas
 #               chmod +x script.sh 
 #               ./script.sh

 #           - name: Setup Node.js environment  #Configurando node js utilizando un action de la marketplace de actions
 #             uses: actions/setup-node@v4.0.4
 #             with:
 #               node-version: latest #Especificando la version que quiero instalar

            - name: Utilizando mi Action
              uses: ./.github/actions/myaction
              with:
                message: 
            

