name: Hola Mundo #Nombre de mi workflow

on: [push, pull_request] # Mi workflow se va a ejecutar cuando se dispare uno de estos eventos en mi repositorio.

jobs: # Primera tarea que va a ejecutar mi workflow.
    hola:
        runs-on: ubuntu-latest

        steps: #Primer paso que va a dar mi job.
            - name: Hola Mundo #Paso 1
              run: echo "Hola Mundo"

            - name: touch file
              run: touch file.txt

            - name: Set text
              run: echo "Hola Thalia" > file.txt  

            - name: Read file
              run: cat file.txt  

    otrojob:
        runs-on: ubuntu-latest
        needs: hola
        steps:
            - name: Hola Mundo2
              run: echo "Hola Mundo2"

