name: Trabajando con secretos
#Los secretos son parecido a las variables, pero su funcionalida es guardar informaciones sensibles.

on: [push]

jobs:

    MiPrimerSecreto:
        runs-on: ubuntu-latest

        steps:
            - name: Mi primer secreto
              run: echo "Mi primer secreto es este, ${{ secrets.MYSECRETGITHUB }}."