name: Variables de entorno


#Existen diferente manera de como usar o acceder a las variables de entorno. (Global, desde mi step y en el apartado de Secrets y Variables en GitHub)
on: [push]

jobs:

    MiPrimeraVariable:
        runs-on: ubuntu-latest


        env: #Directiva
            MY_VAR: Valor de la variable global

        steps:
                
            - name: Viendo mi primera variable global
              run: echooo "Imprimiendo mi primera variable, $MY_VAR"

            - name: Viendo mi segunda variable step
              if: success()
              env:
                MY_VAR_STEP: Mi valor desde step
              run: echo "Imprimiendo mi primera variable, $MY_VAR_STEP"    
              
            - name: Viendo mi tercera variable desde GitHub
              run: echo "Imprimiendo mi primera variable, ${{ vars.myVariableGitHub }}"                 